- name: weshopify-svc-registry-playbook
  hosts: docker-host
  become: 'yes'
  become_user: docker-admin
  tasks:
    - name: create an app directory
      shell: mkdir /app-dir && chmod 777 /app-dir
