- name: weshopify-svc-registry-playbook
  hosts: docker-host
  become: 'yes'
  become_user: docker-admin
  tasks:
    - name: create an app directory
      shell: mkdir app-dir && chmod 777 app-dir

    - name: create artifact target directory
      shell: mkdir app-dir/target && chmod 777 app-dir/target

    - name: copy the jfrog file from ansible to docker
      copy: src=/opt/ci-cd-files/jfrog.sh dest=app-dir

    - name: copy the Dockerfile to Docker server
      copy: src=/opt/ci-cd-files/Dockerfile dest=app-dir
  
    - name: download the artifact from artifactory
      shell: chmod 777 ./app-dir/jfrog.sh && sh ./app-dir/jfrog.sh